# Generated by Django 5.0.6 on 2024-06-25 21:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotelier', '0004_alter_hotelieruser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('total_rooms', models.IntegerField(verbose_name='numero de quartos')),
                ('stars_class', models.IntegerField(verbose_name='numero de estrelas')),
                ('available_rooms', models.IntegerField(default=models.IntegerField(verbose_name='numero de quartos'), verbose_name='quartos disponiveis')),
                ('hotelier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotelier.hotelieruser', verbose_name='hoteleiro')),
            ],
            options={
                'verbose_name': 'hotel',
                'verbose_name_plural': 'hoteis',
            },
        ),
    ]
