# Generated by Django 5.0.6 on 2024-06-25 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        ('hotelier', '0004_alter_hotelieruser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='available_rooms',
            field=models.IntegerField(default=models.IntegerField(verbose_name='numbers of rooms'), verbose_name='number of available rooms'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotelier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotelier.hotelieruser', verbose_name='hotelier'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars_class',
            field=models.IntegerField(verbose_name='number of stars'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='total_rooms',
            field=models.IntegerField(verbose_name='numbers of rooms'),
        ),
        migrations.AlterModelTable(
            name='hotel',
            table='hotel',
        ),
    ]
