# Generated by Django 5.0.6 on 2024-06-25 23:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_hotel_available_rooms_alter_hotel_hotelier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.IntegerField(max_length=3, verbose_name='room number')),
                ('room_type', models.CharField(choices=[], max_length=2, verbose_name='room type')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='daily price')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
                'db_table': 'room',
            },
        ),
    ]
