# Generated by Django 5.0.6 on 2024-06-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='room',
            name='created_at',
        ),
    ]
