# Generated by Django 5.0.6 on 2024-06-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_alter_hotel_available_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotelier',
        ),
    ]
