# Generated by Django 5.0.6 on 2024-06-27 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_remove_hotel_hotelier'),
        ('hotelier', '0019_rename_uuid_hotelieruser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotelier',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotelier.hotelieruser', verbose_name='hotelier'),
            preserve_default=False,
        ),
    ]
