# Generated by Django 5.0.6 on 2024-06-28 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_hotel_hotelier'),
        ('hotelier', '0019_rename_uuid_hotelieruser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotelier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='hotelier.hotelieruser', verbose_name='hotelier'),
        ),
    ]
