# Generated by Django 5.0.6 on 2024-06-30 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.hotel', verbose_name='hotel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('T', 'TRIPLE'), ('S', 'SINGLE'), ('D', 'DOUBLE')], max_length=2, verbose_name='room type'),
        ),
    ]
