# Generated by Django 5.0.6 on 2024-07-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0138_alter_hotel_city_alter_hotel_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('D', 'DOUBLE'), ('T', 'TRIPLE'), ('S', 'SINGLE')], max_length=2, verbose_name='room type'),
        ),
    ]
