# Generated by Django 5.0.6 on 2024-07-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0144_hotel_hotel_description_hotel_rating_room_bed_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('T', 'TRIPLE'), ('S', 'SINGLE'), ('D', 'DOUBLE')], max_length=1, verbose_name='room type'),
        ),
    ]
