# Generated by Django 5.0.6 on 2024-07-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0149_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
