version: '3.9'

services:
  api_hotel-drf:
    container_name: api_hotel-drf
    build:
      context: .
    ports:
      - 8000:8000
    volumes:  
      - ./api:/api
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql-db
      - redis-cache
    environment:
      - TZ=America/Sao_Paulo          

  psql-db:
    container_name: psql-db
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
    ports:
      - 5432:5432                             

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: hotel@gmail.com
      PGADMIN_DEFAULT_PASSWORD: hotel123
    depends_on:
      - psql-db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis-cache:
    container_name: redis-cache
    image: redis:alpine
    ports:
      - 6379:6379

  

volumes:
  pgadmin_data:
