version: '3.9'

services:
  api_hotel:
    container_name: api_hotel
    build:
      context: .
    ports:
      - 8000:8000
    volumes:  
      - ./api:/api
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
      - redis
    environment:
      - TZ=America/Sao_Paulo          

  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: hotel@gmail.com
      PGADMIN_DEFAULT_PASSWORD: hotel123
    depends_on:
      - psql
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379

  # celery:
  #   build:
  #       context: .
  #   volumes:
  #     - .:/app
  #   command: celery -A project worker -B --loglevel=info   

  #   depends_on:
  #     - redis
  #   env_file:
  #     - ./dotenv_files/.env      

volumes:
  pgadmin_data:
