# Generated by Django 5.0.6 on 2024-06-16 14:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGuest',
            fields=[
                ('userauth_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('document', models.CharField(max_length=50, unique=True, verbose_name='guest cpf document')),
                ('birthday', models.DateField(default=django.utils.timezone.now, verbose_name='user birthday')),
            ],
            options={
                'verbose_name': 'user_guest',
                'verbose_name_plural': 'user_guests',
                'db_table': 'user_guest',
            },
            bases=('guests.userauth',),
        ),
    ]
