# Generated by Django 5.0.6 on 2024-06-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_remove_userauth_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff user field'),
        ),
    ]
