# Generated by Django 5.0.6 on 2024-06-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_remove_userguest_userauth_ptr_userguest_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGuest',
        ),
    ]
