# Generated by Django 5.0.6 on 2024-06-17 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_delete_userguest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=50, unique=True, verbose_name='guest cpf document')),
                ('birthday', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='user birthday')),
            ],
            options={
                'verbose_name': 'user_guest',
                'verbose_name_plural': 'user_guests',
                'db_table': 'user_guest',
            },
        ),
    ]
