# Generated by Django 5.0.6 on 2024-06-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0008_userguest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauth',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userauth',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userauth',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='userguest',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='userguest',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='userguest',
            name='phone_number',
            field=models.CharField(blank=True, verbose_name='phone number'),
        ),
    ]
