# Generated by Django 5.0.6 on 2024-06-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0010_alter_userauth_type_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userguest',
            options={'verbose_name': 'guest user', 'verbose_name_plural': 'guest user '},
        ),
        migrations.AlterField(
            model_name='userguest',
            name='document',
            field=models.CharField(max_length=50, unique=True, verbose_name='CPF'),
        ),
    ]
