# Generated by Django 5.0.6 on 2024-06-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0013_alter_userguest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='type_user',
            field=models.CharField(choices=[('GS', 'Guest'), ('HL', 'Hotelier')], max_length=2, verbose_name='type of user, hotelier or guest'),
        ),
        migrations.AlterField(
            model_name='userguest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone number'),
        ),
    ]
