# Generated by Django 5.0.6 on 2024-06-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0015_userguest_updated_at_userguest_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauth',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='userauth',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
