# Generated by Django 5.0.6 on 2024-06-26 14:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0016_remove_userauth_uuid_alter_userauth_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userguest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
