# Generated by Django 5.0.6 on 2024-06-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_userguest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userguest',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userguest',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
