# Generated by Django 5.0.6 on 2024-06-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0019_rename_user_userguest_user_auth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userguest',
            old_name='user_auth',
            new_name='auth_id',
        ),
    ]
