# Generated by Django 5.0.6 on 2024-06-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0020_rename_user_auth_userguest_auth_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userguest',
            old_name='auth_id',
            new_name='auth_user',
        ),
    ]
