# Generated by Django 5.0.6 on 2024-06-27 15:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0021_rename_auth_id_userguest_auth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
