# Generated by Django 5.0.6 on 2024-06-27 18:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0022_userauth_uuid_alter_userauth_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractHotelModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
