# Generated by Django 5.0.6 on 2024-07-05 23:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0025_rename_id_userguest_id_trade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userguest',
            name='id_trade',
        ),
        migrations.RemoveField(
            model_name='userguest',
            name='uuid',
        ),
        migrations.AddField(
            model_name='userguest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
