INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'guests',
    'hotelier',
    'hotel',
    'booking',
    'django_celery_beat',
    'drf_spectacular',
    'drf_spectacular_sidecar',
]   