# Generated by Django 5.0.6 on 2024-06-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelier', '0003_hotelieruser_birthday_hotelieruser_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelieruser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone number'),
        ),
    ]
