# Generated by Django 5.0.6 on 2024-06-25 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelier', '0004_alter_hotelieruser_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelieruser',
            options={'verbose_name': 'hotelier', 'verbose_name_plural': 'hoteliers'},
        ),
        migrations.AlterModelTable(
            name='hotelieruser',
            table='hotelier',
        ),
    ]
