# Generated by Django 5.0.6 on 2024-06-26 12:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelier', '0005_alter_hotelieruser_options_alter_hotelieruser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelieruser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hotelieruser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='hotelieruser',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
