# Generated by Django 5.0.6 on 2024-06-26 13:31

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('hotelier', '0006_hotelieruser_updated_at_hotelieruser_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelieruser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
