# Generated by Django 5.0.6 on 2024-06-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelier', '0010_alter_hotelieruser_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelieruser',
            name='birthday',
        ),
    ]
