# Generated by Django 5.0.6 on 2024-06-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelier', '0014_rename_user_hotelieruser_user_auth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelieruser',
            old_name='user_auth',
            new_name='auth_id',
        ),
    ]
