# Generated by Django 5.0.6 on 2024-06-27 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0023_abstracthotelmodel'),
        ('hotelier', '0016_rename_auth_id_hotelieruser_auth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelieruser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hotelieruser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hotelieruser',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hotelieruser',
            name='uuid',
        ),
        migrations.AddField(
            model_name='hotelieruser',
            name='abstracthotelmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='guests.abstracthotelmodel'),
            preserve_default=False,
        ),
    ]
