# Generated by Django 5.0.6 on 2024-06-27 18:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelier', '0017_remove_hotelieruser_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelieruser',
            name='abstracthotelmodel_ptr',
        ),
        migrations.AddField(
            model_name='hotelieruser',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2024-06-27'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelieruser',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hotelieruser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
