# Generated by Django 5.0.6 on 2024-06-28 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelier', '0019_rename_uuid_hotelieruser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelieruser',
            old_name='id',
            new_name='hotel_id',
        ),
    ]
