# Generated by Django 5.0.6 on 2024-06-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelier', '0020_rename_id_hotelieruser_hotel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelieruser',
            old_name='hotel_id',
            new_name='id',
        ),
    ]
