# Generated by Django 5.0.6 on 2024-07-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'booking', 'verbose_name_plural': 'bookings'},
        ),
        migrations.AlterModelTable(
            name='booking',
            table='booking',
        ),
    ]
