# Generated by Django 5.0.6 on 2024-07-05 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_options_alter_booking_table'),
        ('guests', '0024_delete_abstracthotelmodel'),
        ('hotel', '0066_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='guests.userguest', verbose_name='guest'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='hotel.room', verbose_name='room'),
        ),
    ]
