# Generated by Django 5.0.6 on 2024-07-05 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_end_date_alter_booking_guest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guest',
        ),
    ]
