# Generated by Django 5.0.6 on 2024-07-05 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_guest'),
        ('guests', '0026_remove_userguest_id_trade_remove_userguest_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='guests.userguest', verbose_name='guest'),
            preserve_default=False,
        ),
    ]
