# Generated by Django 5.0.6 on 2024-07-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='days',
            field=models.PositiveIntegerField(default=1, verbose_name='days'),
        ),
    ]
