# Generated by Django 5.0.6 on 2024-07-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='days',
            field=models.PositiveIntegerField(verbose_name='days'),
        ),
    ]
